version: '3.7'
services:
    postgres:
        container_name: orange-postgres
        image: postgres
        restart: always
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres  

        ports: 
            - "5432:5432"
        networks:
            - orange
        volumes: 
            - ./docker/database/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

    cqa:
        build:
            context: .
            target: DEV
        ports: 
            - "3000:3000"        
        networks:
            - orange
        depends_on:
            - postgres

networks:
    orange:
        driver: bridge